- name: Deploy Kubernetes manifests
  hosts: minikube_cat
  become: true
  become_user: ubuntu
  tasks:
    - name: Ensure k8s-manifests directory exists
      ansible.builtin.file:
        path: "/tmp/k8s-manifests"
        state: directory
        mode: '0755'

    - name: Copy Kubernetes manifests to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/k8s-manifests/"
        mode: '0644'
      loop:
        - ../../k8s/namespace.yaml
        - ../../k8s/redis-deployment.yaml
        - ../../k8s/redis-service.yaml
        - ../../k8s/python-cat-deployment.yaml
        - ../../k8s/python-cat-service.yaml
      loop_control:
        label: "{{ item }}"

    - name: Apply Kubernetes manifests
      ansible.builtin.command:
        cmd: kubectl apply -f {{ item }}
      loop:
        - /tmp/k8s-manifests/namespace.yaml
        - /tmp/k8s-manifests/redis-deployment.yaml
        - /tmp/k8s-manifests/redis-service.yaml
        - /tmp/k8s-manifests/python-cat-deployment.yaml
        - /tmp/k8s-manifests/python-cat-service.yaml
      loop_control:
        label: "{{ item }}"
      register: kubectl_apply_result
      changed_when: "'configured' in kubectl_apply_result.stdout or 'created' in kubectl_apply_result.stdout"
