- name: Deploy Kubernetes manifests
  hosts: minikube_cat
  become: true
  become_user: ubuntu
  vars:
    EXTRA_KUBECTL_ARGS: "{{ lookup('env', 'EXTRA_KUBECTL_ARGS') | default('') }}"
  tasks:
    - name: Copy Kubernetes manifests to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/k8s-manifests/"
        mode: '0644'
      loop:
        - ../../k8s/namespace.yaml
        - ../../k8s/redis-deployment.yaml
        - ../../k8s/redis-service.yaml
        - ../../k8s/python-cat-deployment.yaml
        - ../../k8s/python-cat-service.yaml
      loop_control:
        label: "{{ item }}"

    - name: Apply Kubernetes manifests
      ansible.builtin.shell: |
        kubectl apply -f {{ item }} {{ EXTRA_KUBECTL_ARGS }}
      loop:
        - /tmp/k8s-manifests/namespace.yaml
        - /tmp/k8s-manifests/redis-deployment.yaml
        - /tmp/k8s-manifests/redis-service.yaml
        - /tmp/k8s-manifests/python-cat-deployment.yaml
        - /tmp/k8s-manifests/python-cat-service.yaml
      loop_control:
        label: "{{ item }}"
      register: kubectl_apply_result

    - name: Display kubectl apply results
      ansible.builtin.debug:
        msg: "{{ kubectl_apply_result.results | map(attribute='stdout') | list }}"
