- name: Deploy Kubernetes manifests
  hosts: minikube_cat
  become: true
  become_user: ubuntu

  tasks:
    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
      loop:
        - ../../k8s/namespace.yaml
        - ../../k8s/redis-deployment.yaml
        - ../../k8s/redis-service.yaml
        - ../../k8s/python-cat-deployment.yaml
        - ../../k8s/python-cat-service.yaml
      loop_control:
        label: "{{ item }}"

    - name: Create GHCR imagePullSecret
      ansible.builtin.shell: |
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username="{{ lookup('ansible.builtin.env', 'GHCR_USERNAME') }}" \
          --docker-password="{{ lookup('ansible.builtin.env', 'GHCR_TOKEN') }}" \
          --docker-email="unused@example.com" \
          --namespace python-cat \
          --dry-run=client -o yaml | kubectl apply -f -