name: Create and publish Helm Chart

# Configures this workflow to run when a tag is pushed.
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write   

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm login to GitHub Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Lint Helm charts
        run: |
            for chart in helm/*; do
                helm lint "$chart"
            done
        
      - name: Package Helm charts and push to GitHub Packages
        run: |
            for chart in helm/*; do
                pkg=$(helm package "$chart" | awk '{print $NF}')
                helm push "$pkg" oci://ghcr.io/fortunexfortune
            done
